



export const Tableau1 = [
    {
        Id: '0',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '1. La gestion d’un processus d’évaluation',
        Duree: 'Vital',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '1',
        Formation: 'bobo',
        Cible: 'la pluie fait le beau temps et on peut ramasser des mangues a volontés',
        Format: 'ombroise',
        Mode: 'catalogne',
        Theme: 'la pluie fait le beau temps et on peut ramasser des mangues a volontés',
        Duree: 'Chancel',
        Certificat: 'exact',
        Modalite: 'veillez vous inscrire convenablement',
    },
    {
        Id: '2',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '3. Démarche d’élaboration d’une politique publique',
        Duree: 'Donald',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '3',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '4. Analyse des politiques publiques',
        Duree: 'Nelson',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '4',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '5. Evaluation des politiques publiques',
        Duree: 'Auriol',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '5',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '6. Estimation d’impact avec stata',
        Duree: 'Olly Murs',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '6',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '7. Analyse de régression',
        Duree: 'Sam Smith',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '7',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '8. Introduction à stata pour l’analyse des données d’impact',
        Duree: 'GIMS',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '8',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '9. Exemple d’outils de Suivi des ODD',
        Duree: 'Lewis Capaldi',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    },
    {
        Id: '9',
        Formation: 'Formation thématique',
        Cible: 'Cadres des institutions au niveau national et au niveau local',
        Format: 'Séminaire',
        Mode: 'Présentiel',
        Theme: '10. Renforcement de capacité en plaidoyer et veille citoyenne',
        Duree: 'Ya Levis',
        Certificat: 'Oui',
        Modalite: 'Inscription et participation payantes',
    }
   
  ];